alias neovim="nvim --clean"
alias n="nvim"
alias la="lsd -a"
alias os="fastfetch"
alias c="z"
alias fresh="yay -Syu"
alias Fresh="sudo pacman -Syu"
# alias book="mdbook serve -o /home/paradoxiao/RustBooks/Course -p 2000"
# alias Book="mdbook serve -o /home/paradoxiao/RustBooks/ByExample -p 3000"
# alias ttest="cargo build"
alias Scc="yay -Scc"
alias scc="sudo pacman -Scc"
alias yc="yay -Yc"
alias cls="clear"
alias Hybrid="supergfxctl -m Hybrid"
alias Integrated="supergfxctl -m Integrated"
alias bing="ping bing.com"
alias lg="lazygit"
# alias Book="rustup doc --book"
# alias book="xdg-open file:///home/paradoxiao/Codes/Rust/trpl-zh-cn/book/html/index.html"
#alias yy=yazi
#alias gcc="gcc -std=c23"
#alias g++="g++ -std=c++23"
